### ISSUE TITLE
move tests to configuration/example files

### ISSUE THREAD

**Issue by mbaudis** [NBISweden/beacon-api-tests#32]
Tests should not be hard coded in `test_counts.py` etc. but moved to configuration files (`....yaml`).

**Comment by kusalananda** [comment]
This is a suggestion that we're now implementing.

**Comment by mbaudis** [comment]
Great - we're also working on an evaluation of the tests; more later from @KyleGao.

**Comment by MalinAhlberg** [comment]
Hi @mbaudis ! We have now made a version with yaml-tests. It would be great if you could have a look at the pull request: https://github.com/NBISweden/beacon-api-tests/pull/38
