### ISSUE TITLE
Running error after the new update

### ISSUE THREAD

**Issue by KyleGao** [NBISweden/beacon-api-tests#40]
After the latest update, got the following errors.
When revert to the last version, the error goes away.

```
$ python beacon_api_tester.py --host sv 
INFO: Running api tests...
Traceback (most recent call last):
  File "beacon_api_tester.py", line 85, in <module>
    utils.setup.Settings().set_args(c_args)
  File "/Users/gaobo/Desktop/projects/Beacon_Test/beacon-api-tests/utils/setup.py", line 72, in set_args
    for pathname in c_args.test:
TypeError: 'NoneType' object is not iterable
```

**Comment by MalinAhlberg** [comment]
Oh, I think the documentation is a bit outdated, sorry about that!
Try `python beacon_api_tester.py --host http://localhost:5050 --test tests/test-v101-counts.yaml`. Let me know if it still doesn't work!
I'll create an issue about updating the documentation.

**Comment by KyleGao** [comment]
Now it works, thx!
